#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[workspace]

resolver = "2"

members = [
    "crates/root-task",
    "crates/crate-consts",
    "crates/task-helper",
    "crates/kernel-thread",
    "crates/common",
    "crates/shim",
]
