[package]
name = "task-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sel4 = { git = "https://github.com/rel4team/rust-sel4", branch = "mi_dev" }
xmas-elf = "0.9.1"
