[package]
name = "example"
version = "0.1.0"
authors = ["Nick Spinale <nick.spinale@coliasgroup.com>"]
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
sel4 = { git = "https://gitlab.com/coliasgroup/rust-seL4" }
sel4-root-task = { git = "https://gitlab.com/coliasgroup/rust-seL4" }
