#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#
[build]
target = "support/targets/aarch64-sel4.json"

[unstable]
unstable-options = true
build-std = ["core", "alloc"]

[env]
RUST_TARGET_PATH = { value = "support/targets", relative = true }
SEL4_PREFIX = { value = "/Users/jackhu/src_code/rust/sel4-rel4/sel4/install" }
