#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[env]
RUST_TARGET_PATH = { value = "support/targets", relative = true }
SEL4_PREFIX = { value = "/opt/seL4", relative = false }
# SEL4_PREFIX = { value = "/Users/jackhu/src_code/rust/sel4-rel4/sel4/install" }

[build]
target = "aarch64-sel4"

[unstable]
unstable-options = true
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
